add optional default user in migrations
benthomasson/ansible-events-ui pull request #37
Opened 2022-08-02 14:59 UTC by Alex-Izquierdo

Add an optional parameter in migrations to seed a default user and enables it in the docker-compose. 
Documentation updated

2022-08-02 14:59 UTC, Alex-Izquierdo commented
@cutwater please review.

2022-08-02 16:52 UTC, cutwater requested changes
@Alex-Izquierdo I don't think seeding database with default data for a development environment is a good idea. While I don't have strong arguments arguments against your approach, I have a feeling that it might get easily over- and wrongly used besides the development environment. 

* From the state of the database it is impossible track which options were use for applying each migration. 
* In general migrations should not heavily depend on an external parameters, as they tend to change, but applied migrations don't.
* Hardcoded weak password is a concern.

2022-08-02 16:52 UTC, cutwater commented on ansible_events_ui/db/migrations/script.py.mako
> +from alembic import context
I don't think that changes in the template are necessary. Normally database migrations will include only schema migrations, so in my opinion it is redundant to use this template for all generated revisions.

2022-08-02 16:52 UTC, cutwater commented on ansible_events_ui/db/migrations/script.py.mako
> +    if context.get_x_argument(as_dictionary=True).get('create_default_user', None):
`create_default_user` is a local option. It definitely shouldn't go into a template.

2022-08-03 10:55 UTC, Alex-Izquierdo commented
Ok @cutwater Let's discuss it with the team and I can close it or apply your changes.

2022-08-03 13:45 UTC, Alex-Izquierdo commented
Agreed to find a better way to create it.

2022-08-03 13:45 UTC, closed without merging