Adds run_job
benthomasson/ansible-events-ui pull request #42
Opened 2022-08-05 20:48 UTC by benthomasson

2022-08-08 09:00 UTC, cutwater requested changes

2022-08-08 09:00 UTC, cutwater commented on ansible_events_ui/api.py
> +    j: JobInstance, db: AsyncSession = Depends(get_db_session)
Please use more descriptive variables names. Single character variables should be avoided unless they're used as a loop index or their scope is narrow.

`j` is typically used as a loop index.

2022-08-08 09:07 UTC, cutwater commented on ansible_events_ui/api.py
> +    task = asyncio.create_task(
I think we should document somewhere (if it hasn't been done already) that the tasking system implementation we use brings a limitation on number of worker processes that are used to run the application. The application is limited to only a single process mode and will have unexpected side effects if run in multi process mode.

2022-08-08 09:07 UTC, cutwater commented
@benthomasson 

I think we should document somewhere (if it hasn't been done already) that the tasking system implementation we use brings a limitation on number of worker processes that are used to run the application. The application is limited to only a single process mode and will have unexpected side effects if run in multi process mode.

2022-08-11 12:40 UTC, benthomasson commented
@cutwater  At this point, this server is only meant to work in single process mode.   In the future, multiple process mode can be supported if it is needed to meet some performance target that single process mode fails to support.

2022-08-11 12:43 UTC, benthomasson commented
@lgalis please review the UI portions of this PR.

2022-08-11 13:51 UTC, lgalis approved these changes

2022-08-15 18:42 UTC, merged