Add DELETE endpoint for project, activation_instance, job_instance
benthomasson/ansible-events-ui pull request #82
Opened 2022-08-26 15:47 UTC by abaiken

### Ticket: [AAP-5241](https://issues.redhat.com/browse/AAP-5241) API Endpoints for DELETE:

- API: /project/<:id> endpoint DELETE

- API: /job_instance/<:id> endpoint DELETE

- API: /activation_instance/<:id> endpoint DELETE

### Manual testing instructions 
#### Setup 
1. Pull this branch and bring up the project 
2. Via the UI add a project (I used [https://github.com/benthomasson/eda-project](http://localhost:8080/eda/project/2) for testing) - confirm that inventories, extra vars, and playbooks were created when the project was added
3. Add a rulebook activation and confirm that it kicks off a job
#### Test DELETE api/job_instance/ID/
1. Verify that a job exists in the UI and look at the ID
2. Using postman or curl send a DELETE request to http://localhost:8080/api/job_instance/ID/
3. Check the UI and see that the job is no longer there (you can also verify this in the DB) 
#### Test DELETE api/activation_instance/ID/
1. Verify the activation ID in the UI 
2. Using postman or curl send a DELETE request to http://localhost:8080/api/activation_instance/ID/
3. Check the UI and see that the activation is no longer there (you can also verify this in the DB) 
#### Test DELETE api/project/ID/
1. Verify the project ID in the UI (also verify that the project created objects for extra vars/inventories/playbooks/rulesets
2. Using postman or curl send a DELETE request to http://localhost:8080/api/project/ID/
3. Check the UI and see that the project is no longer there (you can also verify this in the DB). Deleting the project should also delete the extra vars/ rulesets/ playbooks/ and inventories
### More context for this PR  
This PR is in kind of a weird state since the API tickets that Shannon and Doston are working on are moving api functions out of the init file into their own files - but I did not want to duplicate work here. I am totally fine with waiting until their PRs are merged and then updating mine accordingly. However, I wanted to put it out there for feedback.

2022-08-26 16:15 UTC, cutwater requested changes

2022-08-26 16:15 UTC, cutwater commented on ansible_events_ui/api/__init__.py
> +    return
1. An empty `return` statement is redundant here.

2. However you may consider returning a `204 No Content` status for DELETE operations though.
    > If a DELETE method is successfully applied, the origin server SHOULD send
    > * a [202 (Accepted)](https://www.rfc-editor.org/rfc/rfc9110.html#status.202) status code if the action will likely succeed but has not yet been enacted,
    > * a [204 (No Content)](https://www.rfc-editor.org/rfc/rfc9110.html#status.204) status code if the action has been enacted and no further information is to be supplied, or
    > * a [200 (OK)](https://www.rfc-editor.org/rfc/rfc9110.html#status.200) status code if the action has been enacted and the response message includes a representation describing the status.

    https://www.rfc-editor.org/rfc/rfc9110.html#DELETE


3. In addition to that normally a REST API server should return HTTP 404 if the resource doesn't exist.

2022-08-26 16:15 UTC, cutwater commented on ansible_events_ui/api/__init__.py
> +    return
ditto

2022-08-26 16:15 UTC, cutwater commented on ansible_events_ui/api/__init__.py
> +    return
ditto

2022-08-26 16:15 UTC, cutwater commented on ansible_events_ui/db/migrations/versions/202208251533_e8c177b90812_add_cascade_deletes.py
> +    # ### end Alembic commands ###
Please remove these comments after migration is verified.

2022-08-26 16:15 UTC, cutwater commented on ansible_events_ui/db/migrations/versions/202208251533_e8c177b90812_add_cascade_deletes.py
> +    # ### commands auto generated by Alembic - please adjust! ###
same here

2022-08-26 20:04 UTC, cutwater reviewed
Minor comments. Otherwise LGTM.

2022-08-31 11:45 UTC, benthomasson commented
@abaiken rebase please

2022-08-31 14:46 UTC, abaiken commented on ansible_events_ui/api/__init__.py
> +@router.delete("/api/project/{project_id}", status_code=204)
👍  Added operation_id to all the deletes

2022-08-31 17:58 UTC, benthomasson approved these changes

2022-08-31 17:58 UTC, merged